'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SystemQueryResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Table_Viewer.SystemQueryResource", GetType(SystemQueryResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT	t.[object_id] AS &quot;TableObjectID&quot;, ix.index_id AS &quot;IndexID&quot;,
        '''ix.name AS &quot;IndexName&quot;,
        '''&apos;[&apos; + s.name + &apos;].[&apos; + t.name + &apos;]&apos; AS &quot;TableName&quot;,
        '''ROUND(avg_fragmentation_in_percent, 2) AS &quot;FragementPct&quot;,
        '''(CASE WHEN ps.avg_fragmentation_in_percent &gt; 15 THEN &apos;REBUILD&apos; ELSE &apos;REORGANIZE&apos; END) AS &quot;Status&quot;,
        '''(
        '''	&apos;ALTER INDEX [&apos; + ix.name + &apos;] ON [&apos; + s.name + &apos;].[&apos; + t.name + &apos;] &apos; +
        '''	(CASE WHEN ps.avg_fragmentation_in_percent &gt; 15 THEN &apos;REBUILD&apos; ELSE &apos;REORGANIZE&apos; END) +
        '''	(CASE WHEN pc.partition_count &gt; 1 THEN  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property CheckIndicesFragmentation() As String
            Get
                Return ResourceManager.GetString("CheckIndicesFragmentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT ta.[object_id], sc.name AS &quot;schema_name&quot;, ta.name AS &quot;table_name&quot;, pa.rows AS &quot;rows&quot;
        '''FROM sys.tables AS ta
        '''INNER JOIN sys.partitions AS pa
        '''ON pa.OBJECT_ID = ta.OBJECT_ID
        '''INNER JOIN sys.schemas AS SC
        '''ON ta.schema_id = sc.schema_id
        '''WHERE ta.is_ms_shipped = 0
        '''AND pa.index_id IN (1,0)
        '''ORDER BY sc.name, ta.name.
        '''</summary>
        Friend Shared ReadOnly Property CountTableRows() As String
            Get
                Return ResourceManager.GetString("CountTableRows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EXEC sp_change_users_login &apos;Auto_Fix&apos;, @user.
        '''</summary>
        Friend Shared ReadOnly Property FixOrphanedUser() As String
            Get
                Return ResourceManager.GetString("FixOrphanedUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT sc.name AS &quot;ColumnName&quot;,
        '''sep.value AS &quot;Description&quot;
        '''FROM sys.columns AS sc
        '''INNER JOIN sys.extended_properties sep 
        '''ON sc.[object_id] = sep.major_id
        '''AND sc.column_id = sep.minor_id
        '''AND sep.name = &apos;MS_Description&apos;
        '''WHERE sc.[object_id] = @ObjectID.
        '''</summary>
        Friend Shared ReadOnly Property GetAllColumnDesc() As String
            Get
                Return ResourceManager.GetString("GetAllColumnDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT obj.[object_id] AS &quot;ObjectId&quot;,
        '''c.column_id AS &quot;ColumnId&quot;,
        '''sch.name AS &quot;Schema&quot;,
        '''obj.name AS &quot;ObjectName&quot;,
        '''sch.name + &apos;.&apos; + obj.name AS &quot;FullName&quot;,
        '''c.name AS &quot;ColumnName&quot;, 
        '''st.name + (CASE st.name
        '''WHEN &apos;numeric&apos; THEN &apos;(&apos; + CAST(c.precision AS nvarchar) + &apos;,&apos; + CAST(c.scale AS nvarchar) + &apos;)&apos;
        '''WHEN &apos;decimal&apos; THEN &apos;(&apos; + CAST(c.precision AS nvarchar) + &apos;,&apos; + CAST(c.scale AS nvarchar) + &apos;)&apos;
        '''WHEN &apos;varchar&apos; THEN &apos;(&apos; + CAST(c.max_length AS nvarchar) + &apos;)&apos;
        '''WHEN &apos;nvarchar&apos; THEN &apos;(&apos; + CAST((c.max_lengt [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property GetAllColumns() As String
            Get
                Return ResourceManager.GetString("GetAllColumns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT mp.name AS DatabaseUser, rp.name AS DatabaseRole
        '''FROM sys.database_role_members drm
        '''INNER JOIN sys.database_principals rp
        '''ON drm.role_principal_id = rp.principal_id
        '''INNER JOIN sys.database_principals mp 
        '''ON drm.member_principal_id = mp.principal_id.
        '''</summary>
        Friend Shared ReadOnly Property GetAllUserRoles() As String
            Get
                Return ResourceManager.GetString("GetAllUserRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT [d].[name] ,
        '''[d].[create_date] ,
        '''[d].[compatibility_level] ,
        '''[d].[collation_name] ,
        '''r.restore_history_id,
        '''r.restore_type, r.backup_set_id, r.user_name,
        '''r.restore_date, r.replace, r.recovery, r.restart
        '''FROM master.sys.databases d
        '''LEFT OUTER JOIN msdb.dbo.[restorehistory] r
        '''ON r.[destination_database_name] = d.Name
        '''WHERE d.Name = DB_NAME()
        '''ORDER BY r.restore_date DESC.
        '''</summary>
        Friend Shared ReadOnly Property GetDatabaseRestoreHistory() As String
            Get
                Return ResourceManager.GetString("GetDatabaseRestoreHistory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT f.file_id, f.type_desc, f.name AS &quot;FileName&quot;, f.physical_name AS &quot;FilePath&quot;
        '''FROM sys.master_files AS f
        '''INNER JOIN sys.databases AS db
        '''ON f.database_id = db.database_id
        '''WHERE db.name = @name.
        '''</summary>
        Friend Shared ReadOnly Property GetDatabasesFiles() As String
            Get
                Return ResourceManager.GetString("GetDatabasesFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EXEC sp_change_users_login &apos;Report&apos;.
        '''</summary>
        Friend Shared ReadOnly Property GetOrphanedUsers() As String
            Get
                Return ResourceManager.GetString("GetOrphanedUsers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM SYS.SYNONYMS ORDER BY type, name.
        '''</summary>
        Friend Shared ReadOnly Property GetSynonyms() As String
            Get
                Return ResourceManager.GetString("GetSynonyms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT fk.[object_id] AS &apos;const_object_id&apos;, fk.name, pc.name AS &quot;parent_col&quot;, rt.[object_id] AS &quot;ref_object_id&quot;, rtm.name AS &quot;ref_schema&quot;, rt.name AS &quot;ref_table&quot;, rc.name AS &quot;ref_col&quot;
        '''FROM sys.foreign_keys AS fk
        '''INNER JOIN sys.foreign_key_columns AS fkc
        '''ON fk.OBJECT_ID = fkc.constraint_object_id
        '''INNER JOIN sys.columns AS pc
        '''ON fkc.parent_object_id = pc.[object_id]
        '''AND fkc.parent_column_id = pc.column_id
        '''INNER JOIN sys.objects AS rt
        '''ON fkc.referenced_object_id = rt.[object_id]
        '''INNER JOIN sys.schemas [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property GetTableForeignKeys() As String
            Get
                Return ResourceManager.GetString("GetTableForeignKeys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --DECLARE @object_id int
        '''--DECLARE @index_type nvarchar(10) = &apos;IX&apos;
        '''
        '''DECLARE @is_unique_constraint bit = (CASE @index_type WHEN &apos;UK&apos; THEN 1 WHEN &apos;IX&apos; THEN 0 ELSE NULL END)
        '''
        '''SELECT t.[object_id], i.index_id, OBJECT_SCHEMA_NAME(t.[object_id],DB_ID()) AS &quot;schema&quot;,
        '''t.[name] AS &quot;table_name&quot;, i.[name] AS &quot;index_name&quot;,
        '''ac.column_id, ac.[name] AS &quot;column_name&quot;, ic.key_ordinal, ic.[is_included_column]
        '''--i.[type_desc], i.[data_space_id], i.[ignore_dup_key], i.[is_primary_key]
        '''--i.[is_unique_constraint], i.[fi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property GetTableIndices() As String
            Get
                Return ResourceManager.GetString("GetTableIndices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT i.[object_id],
        '''kc.name AS &quot;object_name&quot;,
        '''c.column_id,
        '''c.[name] AS &quot;column_name&quot;,
        '''ic.key_ordinal
        '''FROM sys.[key_constraints] AS [kc]
        '''INNER JOIN sys.[indexes] AS [i]
        '''ON [i].[object_id] = [kc].[parent_object_id]
        '''AND [i].[index_id] = [kc].[unique_index_id]
        '''INNER JOIN sys.[index_columns] AS [ic]
        '''ON [ic].[object_id] = [i].[object_id]
        '''AND [ic].[index_id] = [i].[index_id]
        '''INNER JOIN sys.[columns] AS [c]
        '''ON [c].[object_id] = [kc].[parent_object_id]
        '''AND [c].[column_id] = [ic].[column_id]
        '''WHERE kc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property GetTableUniqueKeys() As String
            Get
                Return ResourceManager.GetString("GetTableUniqueKeys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT t.*,
        '''STUFF((
        '''	select &apos;,&apos; + rp.name
        '''	from sys.database_role_members drm
        '''	join sys.database_principals rp on (drm.role_principal_id = rp.principal_id)
        '''	join sys.database_principals mp on (drm.member_principal_id = mp.principal_id)
        '''	where mp.name = t.name
        '''	FOR XML PATH(&apos;&apos;)
        '''), 1, 1, &apos;&apos;) AS [database_roles]
        '''FROM sys.database_principals AS t
        '''ORDER BY t.type DESC, t.name.
        '''</summary>
        Friend Shared ReadOnly Property ListUserRole() As String
            Get
                Return ResourceManager.GetString("ListUserRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DECLARE @fillfactor int = 80
        '''DECLARE @TableName varchar(255)
        '''DECLARE @sql nvarchar(500)
        '''
        '''DECLARE TableCursor CURSOR FOR
        '''SELECT OBJECT_SCHEMA_NAME([object_id]) + &apos;.&apos; + name AS TableName
        '''FROM sys.tables
        '''
        '''OPEN TableCursor
        '''FETCH NEXT FROM TableCursor INTO @TableName
        '''WHILE @@FETCH_STATUS = 0 BEGIN
        '''	
        '''	SET @sql = &apos;ALTER INDEX ALL ON &apos; + @TableName + &apos; REBUILD WITH (FILLFACTOR = &apos; + CONVERT(VARCHAR(3),@fillfactor) + &apos;)&apos;
        '''	EXEC (@sql)
        '''	FETCH NEXT FROM TableCursor INTO @TableName
        '''	
        '''END
        '''CLOSE TableCurs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property RebuildAllIndices() As String
            Get
                Return ResourceManager.GetString("RebuildAllIndices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT obj.*, sch.name AS schema_name
        '''FROM sys.objects AS obj
        '''INNER JOIN sys.schemas AS sch ON obj.schema_id = sch.schema_id
        '''WHERE (obj.[type] = @obj_type OR obj.[type] = @obj_type2)
        '''AND (obj.name like @name OR @name = &apos;&apos; OR @name IS NULL)
        '''AND (sch.name like @schema OR @schema = &apos;&apos; OR @schema IS NULL)
        '''AND ((obj.modify_date &gt;= @modify_dateS AND obj.modify_date &lt;= @modify_dateE) OR (obj.modify_date &gt;= @modify_dateS AND @modify_dateE is null) OR (obj.modify_date &lt;= @modify_dateE AND @modify_dateS is null [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SearchDatabaseObjects() As String
            Get
                Return ResourceManager.GetString("SearchDatabaseObjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WITH cte AS (
        '''	SELECT t.[object_id] AS &quot;TableObjectID&quot;, c.[column_id] AS &quot;ColumnID&quot;, t.name AS &quot;TableName&quot;, c.name AS &quot;ColumnName&quot;, c.is_identity AS &quot;IsIdent&quot;,
        '''	CASE WHEN pkd.[object_id] IS NULL THEN 0 ELSE 1 END AS &quot;IsKey&quot;
        '''	FROM sys.objects AS t
        '''	INNER JOIN sys.all_columns AS c
        '''	ON t.[object_id] = c.[object_id]
        '''	LEFT OUTER JOIN sys.indexes AS pk
        '''	ON c.[object_id] = pk.[object_id]
        '''	AND pk.is_primary_key = 1
        '''	LEFT OUTER JOIN sys.index_columns AS pkd
        '''	ON pk.[object_id] = pkd.[object_id]
        '''	AND pk.[in [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SearchTableByPrimaryKey() As String
            Get
                Return ResourceManager.GetString("SearchTableByPrimaryKey", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
